# Generated by Django 3.0.8 on 2020-08-22 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='lister_id',
        ),
        migrations.AddField(
            model_name='listing',
            name='lister_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lister_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
