# Generated by Django 3.0.8 on 2020-08-22 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200822_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='poster',
        ),
        migrations.AddField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
