# Generated by Django 3.0.8 on 2020-08-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200822_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
